<?php include V_PATH . '/_parts/_head.phtml'; ?>
<div role="main" class="main">
	<?php
	$pageTitle = "About Us";
	include V_PATH . '/_parts/title.phtml';
	?>

	<div class="position-relative">
		<img src="/img/demos/architecture-2/backgrounds/arch-plan-1.jpg" class="img-fluid position-absolute top-0 right-0" alt="" />
	</div>

	<div class="custom-page-wrapper pt-5">
		<div class="container container-xl-custom pt-5 mt-4">
			<div class="row pt-2">
				<div class="col position-relative">
					<div class="position-absolute z-index-0 appear-animation" data-appear-animation="fadeInRightShorter" data-appear-animation-delay="500" style="top: 100px; left: -80px;">
						<h2 class="text-color-dark custom-stroke-text-effect-1 custom-big-font-size-1 font-weight-black opacity-1 mb-0">Energy</h2>
					</div>
					<div class="overflow-hidden mb-2">
						<!-- başlık -->
						<h2 class="text-color-default positive-ls-3 line-height-3 text-4 mb-0 appear-animation" data-appear-animation="maskUp" data-appear-animation-delay="550"><?=LH::t("experience_and_innovation")?></h2>
					</div>

					<div class="appear-animation" data-appear-animation="fadeInUpShorter" data-appear-animation-delay="300">
						<img src="/img/demos/architecture-2/divider.jpg" class="img-fluid opacity-5 mb-4" alt="" />
					</div>
					<p class="custom-font-tertiary text-5 line-height-4 mb-4 appear-animation" data-appear-animation="fadeInUpShorter" data-appear-animation-delay="600"><?=LH::t("watch_the_energy_m")?></p>
					<p class="text-3-5 mb-4 appear-animation" data-appear-animation="fadeInUpShorter" data-appear-animation-delay="300"><?=LH::t("solid_electron_w_o")?> </p>
					<div>
						<div class="overflow-hidden mb-3">
							<h3 class="text-transform-none text-color-dark font-weight-black text-10 line-height-2 mb-0 appear-animation" data-appear-animation="maskUp" data-appear-animation-delay="500"><?=LH::t("our_mission")?></h3>
						</div>
						<p class="text-3-5 mb-4 appear-animation" data-appear-animation="fadeInUpShorter" data-appear-animation-delay="300"> <?=LH::t("we_produce_technologies_a_a")?>
						<p>
					</div>
					<div>
						<div class="overflow-hidden mb-3">
							<h3 class="text-transform-none text-color-dark font-weight-black text-10 line-height-2 mb-0 appear-animation" data-appear-animation="maskUp" data-appear-animation-delay="500"><?=LH::t("our_business_model")?></h3>
						</div>
						<p class="text-3-5 mb-4 appear-animation" data-appear-animation="fadeInUpShorter" data-appear-animation-delay="300"><?=LH::t("we_make_investments_i_a")?>
						<p>
					</div>
					<div>
						<div class="overflow-hidden mb-3">
							<h3 class="text-transform-none text-color-dark font-weight-black text-10 line-height-2 mb-0 appear-animation" data-appear-animation="maskUp" data-appear-animation-delay="500"><?=LH::t("sustainable_energy_efficiency")?></h3>
						</div>
						<p class="text-3-5 mb-4 appear-animation" data-appear-animation="fadeInUpShorter" data-appear-animation-delay="300"><?=LH::t("the_field_devices_w_h")?></p>
					</div>
					<div>
						<div class="overflow-hidden mb-3">
							<h3 class="text-transform-none text-color-dark font-weight-black text-10 line-height-2 mb-0 appear-animation" data-appear-animation="maskUp" data-appear-animation-delay="500"><?=LH::t("our_experience")?></h3>
						</div>
						<p class="text-3-5 mb-4 appear-animation" data-appear-animation="fadeInUpShorter" data-appear-animation-delay="300"><?=LH::t("our_accumulated_knowledge_a_c")?></p>
					</div>


				</div>
			</div>
			<div class="lightbox" data-plugin-options="{'delegate': 'a', 'type': 'image', 'gallery': {'enabled': true}, 'mainClass': 'mfp-with-zoom', 'zoom': {'enabled': true, 'duration': 300}}">
				<div class="row pb-3 mb-4 appear-animation" data-appear-animation="fadeInUpShorterPlus" data-appear-animation-delay="600" data-plugin-options="{'accY': 200}">
					<div class="col-md-4 mb-4 mb-md-0">
						<a class="d-inline-block custom-img-thumbnail-style-1 img-thumbnail img-thumbnail-no-borders img-thumbnail-hover-icon rounded-0" href="/img/demos/architecture-2/generic/generic-11.jpg">
							<img src="/img/agreement.jpg" class="img-fluid rounded-0" alt="" />
						</a>
					</div>
					<div class="col-md-4 mb-4 mb-md-0">
						<a class="d-inline-block custom-img-thumbnail-style-1 img-thumbnail img-thumbnail-no-borders img-thumbnail-hover-icon rounded-0" href="/img/demos/architecture-2/generic/generic-11.jpg">
							<img src="/img/world_in_hand.jpg" class="img-fluid rounded-0" alt="" />
						</a>
					</div>
					<div class="col-md-4">
						<a class="d-inline-block custom-img-thumbnail-style-1 img-thumbnail img-thumbnail-no-borders img-thumbnail-hover-icon rounded-0" href="/img/demos/architecture-2/generic/generic-11.jpg">
							<img src="/img/man_work_city.jpg" class="img-fluid rounded-0" alt="" />
						</a>
					</div>
				</div>
			</div>
			<div class="row pb-5 mb-5">
				<div class="col">
					<div>
						<div class="overflow-hidden mb-3">
							<h3 class="text-transform-none text-color-dark font-weight-black text-10 line-height-2 mb-0 appear-animation" data-appear-animation="maskUp" data-appear-animation-delay="500"><?=LH::t("sustainability")?></h3>
						</div>
						<p class="text-3-5 mb-4 appear-animation" data-appear-animation="fadeInUpShorter" data-appear-animation-delay="300"><?=LH::t("sustainability_is_at_t_c")?></p>
					</div>
					<div>
						<div class="overflow-hidden mb-3">
							<h3 class="text-transform-none text-color-dark font-weight-black text-10 line-height-2 mb-0 appear-animation" data-appear-animation="maskUp" data-appear-animation-delay="500"><?=LH::t("teamwork_and_cooperation")?></h3>
						</div>
						<p class="text-3-5 mb-4 appear-animation" data-appear-animation="fadeInUpShorter" data-appear-animation-delay="300"><?=LH::t("our_team_consists_o_t")?></p>
					</div>
				</div>
			</div>

			<div class="row">
				<div class="col">
					<hr class="my-0">
				</div>
			</div>


		</div>

		<section class="section parallax bg-transparent border-0 py-0 m-0" data-plugin-parallax data-plugin-options="{'speed': 1.5, 'scrollableParallax': true, 'scrollableParallaxMinWidth': 991, 'startOffset': 13, 'cssProperty': 'width', 'cssValueStart': 40, 'cssValueEnd': 100, 'cssValueUnit': 'vw'}">
			<div class="d-flex justify-content-center">
				<div class="scrollable-parallax-wrapper bg-primary overflow-hidden">
					<div class="container container-xl-custom custom-container-style-3 custom-container-position-1 py-5 my-5 mx-0">
						<div class="row justify-content-center pt-3 mb-5">
							<div class="col-sm-8 col-md-12 text-center">


							</div>
						</div>
						<div class="row justify-content-center pb-3">
							<div class="col-lg-9">
								<div class="owl-carousel owl-theme nav-style-1 nav-light nav-outside nav-font-size-lg custom-dots-style-1 custom-dots-style-1-light mb-0" data-plugin-options="{'responsive': {'0': {'items': 1, 'nav': false, 'dots': true}, '576': {'items': 1, 'nav': false, 'dots': true}, '768': {'items': 1, 'nav': false, 'dots': true}, '992': {'items': 1}, '1200': {'items': 1}}, 'loop': false, 'nav': true, 'dots': false}">
									<div>
										<div class="testimonial testimonial-style-2 testimonial-with-quotes testimonial-remove-right-quote custom-testimonial-quote mb-0">
											<blockquote>
												<p class="custom-font-secondary text-color-light opacity-8 font-weight-light line-height-6 text-4-5 px-2 px-lg-3 mb-0"><em><?=LH::t("when_energy_is_u_w")?></em></p>
											</blockquote>
											<div class="testimonial-author">
												<p class="text-color-light font-weight-bold text-4 mb-0">Lao Tzu</p>
											</div>
										</div>
									</div>
									<div>
										<div class="testimonial testimonial-style-2 testimonial-with-quotes testimonial-remove-right-quote custom-testimonial-quote mb-0">
											<blockquote>
												<p class="custom-font-secondary text-color-light opacity-8 font-weight-light line-height-6 text-4-5 px-2 px-lg-3 mb-0"><em><?=LH::t("efficiency_is_never_a_i")?>
													</em></p>
											</blockquote>
											<div class="testimonial-author">
												<p class="text-color-light font-weight-bold text-4 mb-0">Paul J. Meyer</p>
											</div>
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</section>



	</div>

</div>

</div>
</div>
<?php include V_PATH . '/_parts/_footer.phtml'; ?>