<?php include V_PATH . '/_parts/_head.phtml'; ?>
<div role="main" class="main">
    <?php
    $pageTitle = "App-Download";
    include V_PATH . '/_parts/title.phtml';
    ?>

    <section class="ls section_padding_top_50 section_padding_bottom_100 " style="border-top: 1px solid white;margin-top:150px;">
        <div class="container background" id="app_download">


        </div>

        <div class="container" style="box-shadow: rgba(100, 100, 111, 0.2) 0px 7px 29px 0px;">
            <div class="jumbotron p-1 p-md-1 bg-white text-center" style="background-color: transparent !important;">
                <img class="format" src="/img/logos/predixi.png" style="width:35%;margin-top: 3%;">
            </div>
            
            <div class="row" style="margin-top: 5%;">
                <div class="col" style="    margin-bottom: 30px;text-align: center;">
                    <div style="height: 136px !important;     ">

                        <a href="/s/dl/predixi_setup.exe"><img src="/img/app-downloads/win-7.png" class="app-logo" alt="..."><br></a>
                    </div>

                    <a target="_blank" href="/s/dl/predixi_setup.exe"><i class="fa fa-download" aria-hidden="true"></i>&nbsp;&nbsp;FOR WİNDOWS 7
                    </a>

                </div>
                <div class="col" style="    margin-bottom: 30px;text-align: center;">
                    <div style="height: 136px !important;     ">

                        <a href="https://www.microsoft.com/tr-tr/p/predixi-kontrol-sistemi/9n7l3bkqpcx4?activetab=pivot:overviewtab"> <img src="/img/app-downloads/win-10.png" class="app-logo" alt="..."><br></a>
                    </div>

                    <a target="_blank" href="https://www.microsoft.com/tr-tr/p/predixi-kontrol-sistemi/9n7l3bkqpcx4?activetab=pivot:overviewtab"><i class="fa fa-download" aria-hidden="true"></i>&nbsp;&nbsp;FOR WİNDOWS 10
                    </a>
                </div>
                <div class="col" style="    margin-bottom: 30px;text-align: center;">
                    <div style="height: 136px !important;     ">

                        <a href="https://apps.apple.com/tr/app/predixi-gui/id1589777970?l=tr"><img src="/img/app-downloads/iphone.png" class="app-logo" alt="..."><br></a>
                    </div>

                    <a target="_blank" href="https://apps.apple.com/tr/app/predixi-gui/id1589777970?l=tr"><i class="fa fa-download" aria-hidden="true"></i>&nbsp;&nbsp;FOR IPAD / IPHONE
                    </a>
                </div>
                <div class="col" style="    margin-bottom: 30px;text-align: center;">
                    <div style="height: 136px !important;     ">

                        <a href="/s/dl/predixi_setup.dmg"><img src="/img/app-downloads/apple-mac.png" class="app-logo" alt="..."><br></a>
                    </div>

                    <a target="_blank" href="/s/dl/predixi_setup.dmg"><i class="fa fa-download" aria-hidden="true"></i>&nbsp;&nbsp;FOR MAC OS X
                    </a>
                </div>
                <div class="col" style="    margin-bottom: 30px;text-align: center;">
                    <div style="height: 136px !important;     ">

                        <a href="https://play.google.com/store/apps/details?id=com.predixi.gui&gl=TR"><img src="/img/app-downloads/android.png" class="app-logo" alt="..."><br></a>
                    </div>

                    <a target="_blank" href="https://play.google.com/store/apps/details?id=com.predixi.gui&gl=TR"><i class="fa fa-download" aria-hidden="true"></i>&nbsp;&nbsp;FOR ANDROİD
                    </A>
                </div>
                <div class="col" style="    margin-bottom: 30px;text-align: center;">
                    <div style="height: 136px !important;     ">

                        <a href="/s/dl/predixi_setup.tar.gz"><img src="/img/app-downloads/linux.png" class="app-logo" alt="..."><br></a>
                    </div>
                    <a href="/s/dl/predixi_setup.tar.gz"><i class="fa fa-download" aria-hidden="true"></i>&nbsp;&nbsp; FOR LINUX</a>

                </div>
            </div>
            <div class="row-1">
                <ul>
                    <li>
                        <i class="fa fa-book" style="font-size: 18px;" aria-hidden="true"></i>
                        <a class="operating_guide_link" download href="/img/logos/PDF/Predixi-ui-kullanım-kılavuzu.pdf">Predixi UI User Manual</a>
                    </li>
                </ul>

            </div>
        </div>

        <div class="container">

            <div class="row" style="margin-top: 8%;box-shadow: rgba(100, 100, 111, 0.2) 0px 7px 29px 0px;">
                <div class="jumbotron p-1 p-md-1 bg-white text-center" style="background-color: transparent !important;">
                    <img class="format" width="30" src="/img/logos/aqua_guide.png" style="width: 35%">
                </div>
                <div></div>
                <div class="col-7" style="    margin-bottom: 30px;text-align: center;">
                    <div style="height: 136px !important;     ">

                        <a href="https://apps.apple.com/tr/app/predixi-gui/id1589777970?l=tr"><img src="/img/app-downloads/iphone.png" class="app-logo" alt="..."><br></a>
                    </div>

                    <a target="_blank" href="https://apps.apple.com/dk/app/aqua-guide-measure-mate/id6464666278"><i class="fa fa-download" aria-hidden="true"></i>&nbsp;&nbsp;FOR IPAD / IPHONE
                    </a>
                </div>

                <div class="col-3" style="    margin-bottom: 30px;text-align: center;">
                    <div style="height: 136px !important;     ">

                        <a href="https://play.google.com/store/apps/details?id=com.predixi.gui&gl=TR"><img src="/img/app-downloads/android.png" class="app-logo" alt="..."><br></a>
                    </div>

                    <a target="_blank" href="https://play.google.com/store/apps/details?id=guide.aqua.ui"><i class="fa fa-download" aria-hidden="true"></i>&nbsp;&nbsp;FOR ANDROİD
                    </A>
                </div>

            </div>

        </div>

</div>
</section>

<?php include V_PATH . '/_parts/_footer.phtml'; ?>