<?php include V_PATH . '/_parts/_head.phtml'; ?>
<div role="main" class="main">
    <?php
    $pageTitle = "Energy efficiency";
    include V_PATH . '/_parts/title.phtml';
    ?>
    <section class="ls section_padding_top_50 section_padding_bottom_100">
        <div class="container" id="cont_id" style="margin-top:150px;">
            <div class="jumbotron p-1 p-md-1 bg-white">

                <h1 style="color: #343a40; font-weight: 500;">
              
                <p style="color: #343a40; font-weight: 900;">
                <?=LH::t("we_measure_and_a_y")?>            </h1>
            </div>
            <div class="row mb-5 mt-5">
                <div class="col-md-6 mb-1 mt-5-1" style="text-align: justify;">
                 
                    <p style=" color: #343a40; font-weight: 600;">
                    <b style="color: #343a40; font-weight: bold;font-size: 18px;"><?=LH::t("measurement_services")?>  </b><p style=" color: #343a40; font-weight: normal;">
                    <?=LH::t("in_pump_systems_i")?> </p>
                </div>
                <div class="col-md-6 mb-1 mt-5-1">
                    <img style="width:50%" src="/img/predixi/enerji_verimlilik_sol.jpg"><img style="width:50%" src="/img/predixi/enerji_verimlilik_sag.jpg" alt=""><br>
                    <p></p>
                </div>
            </div>
            <hr>
            <div class="row mb-5 mt-5">
                <div class="col-md-6 mb-1 mt-5-1">

                    <img style="width:50%;" src="/img/predixi/enerji_verimlilik_sol_2.jpg"><br>
                    <p></p>
                </div>
                <div class="col-md-6 mb-1 mt-5-1" style="text-align: justify;">
                    <b style="color: #343a40; font-weight: bold;font-size: 18px;"> <?=LH::t("key_delivery_productivity_p")?></b><br>
                    <p style="color: #343a40; font-weight: 600;">
                    <p style="color: #343a40; font-weight: normal;">
                    <?=LH::t("according_to_the_m_r")?></p>
                </div>
            </div>
            <hr>
            <div class="row mb-5 mt-5">
                <div class="col-md-6 mb-1 mt-5-1">
                    <b style="color: #343a40; font-weight: bold;font-size: 18px;"><?=LH::t("pm_motor_technology")?></b><br>
                    <p style="color: #343a40; font-weight: 600;text-align: justify;">
                    <p style="color: #343a40; font-weight: normal;text-align: justify;">
                    <?=LH::t("we_supply_high_e_f")?></p>
                </div>
                <div class="col-md-6 mb-1 mt-5-1" style="text-align: right;">
                    <img style="width:50%" src="/img/predixi/enerji_verimlilik_alt.jpg"><br>
                    <p></p>
                    <p></p>
                </div>
            </div>
            <hr>
            <div class="row mb-5 mt-5">
                <div class="col-md-12 mb-4 text-center">
                    <b style="color: #605e5e;font-weight:600;font-size:27px;"><?=LH::t("water_sewerage_administration_a_g")?></b>
                </div>
                <div class="col-md-12" style="margin-top: 1%;text-align: justify;">
                    <p style="color: #343a40; font-weight: 600;">
                    <p style="color: #343a40; font-weight: normal;">
                    <?=LH::t("today_the_c_p")?></p>
                </div>
            </div>
            <div class="row mb-5 mt-5">
                <div class="col-md-6 mb-1 mt-5-1">
                    <img style="width: 100%" src="/img/terfi_merkezi.png"><br>
                    <p></p>
                </div>
                <div class="col-md-6 mb-1 mt-5-1" style="text-align: justify;">
                    <b style="color: #343a40; font-weight: bold;font-size: 18px;"><?=LH::t("promotion_centers")?></b><br>
                    <p style="color: #343a40; font-weight: 600;"><?=LH::t("we_encounter_many_p_c")?></p>
                </div>
            </div>
            <hr>
            <div class="row mb-5 mt-5">
                <div class="col-md-6 mb-1 mt-5-1">
                    <b style="color: #343a40; font-weight: bold;font-size: 18px;"><?=LH::t("wastewater_promotion_centers")?></b><br>
                    <p style="color: #343a40; font-weight: 600;text-align: justify;">
                    <p style="color: #343a40; font-weight: normal;text-align: justify;">
                    <?=LH::t("waste_water_should_b_t")?></p>
                </div>
                <div class="col-md-6 mb-1 mt-5-1" style="text-align: right;">
                    <img style="width: 100%" src="/img/atiksu_terfi_merkezi.jpg"><br>
                    <p></p>
                    <p></p>
                </div>
            </div>
            <hr>
            <div class="row mb-5 mt-5">
                <div class="col-md-6 mb-1 mt-5-1">
                    <img src="/img/icme_su.jpg"style="width:100%"><br>
                    <p></p>
                </div>
                <div class="col-md-6 mb-1 mt-5-1" style="text-align: justify;">
                    <b style="color: #343a40; font-weight: bold;font-size: 18px;"><?=LH::t("drinking_water_tanks")?></b><br>
                    <p style="color: #343a40; font-weight: 600;">
                    <p style="color: #343a40; font-weight: normal;">
                    <?=LH::t("water_collected_from_u_a")?></p>
                </div>
            </div>
            <hr>
            <div class="row mb-5 mt-5">
                <div class="col-md-6 mb-1 mt-5-1">
                    <b style="color: #343a40; font-weight: bold;font-size: 18px;"><?=LH::t("network_pressure_control_a_m")?></b><br>
                    <p style="color: #343a40; font-weight: 600;text-align: justify;">
                    <p style="color: #343a40; font-weight: normal;text-align: justify;">
                    <?=LH::t("there_is_a_p_c")?></p>
                </div>
                <div class="col-md-6 mb-1 mt-5-1" style="text-align: right;">
                    <img src="/img/basinc_kontrol.jpg"><br>
                    <p></p>
                    <p></p>
                </div>
            </div>
            <hr>
            <div class="row mb-5 mt-5">
                <div class="col-md-6 mb-1 mt-5-1">
                    <img src="/img/su_kuyulari.jpg"style="width:100%"><br>
                    <p></p>
                </div>
                <div class="col-md-6 mb-1 mt-5-1" style="text-align: justify;">
                    <b style="color: #343a40; font-weight: bold;font-size: 18px;"> <?=LH::t("water_wells")?></b><br>
                    <p style="color: #343a40; font-weight: 600;">
                    <p style="color: #343a40; font-weight: normal;">
                    <?=LH::t("the_first_step_o_t")?></p></div>
            </div>
            <hr>
            <div class="row mb-5 mt-5">
                <div class="col-md-12 mb-4 text-center">
                    <b style="color: #605e5e;font-weight:600;font-size:27px;"><?=LH::t("special_water_solutions_f_i")?></b>
                </div>
                <div class="col-md-12" style="margin-top: 1%;text-align: justify;">
                    <p style="color: #343a40; font-weight: 600;">
                    <p style="color: #343a40; font-weight: normal;">
                    <?=LH::t("water_pumps_are_u_i")?></p>
                </div>
            </div>
            <div class="row mb-5 mt-5">
                <div class="col-md-6 mb-1 mt-5-1">
                    <b style="color: #343a40; font-weight: bold;font-size: 18px;"><?=LH::t("water_cooling_tower")?></b><br>
                    <p style="color: #343a40; font-weight: 600;text-align: justify;">
                    <p style="color: #343a40; font-weight: normal;text-align: justify;">
                    <?=LH::t("in_water_cooling_t")?></div>
                <div class="col-md-6 mb-1 mt-5-1" style="text-align: right;">
                    <img style="width: 100%" src="/img/su_sogutma_kulesi.jpeg"><br>
                    <p></p>
                    <p></p>
                </div>
            </div>
            <hr>
            <div class="row mb-5 mt-5">
                <div class="col-md-6 mb-1 mt-5-1">
                    <img style="width: 100%" src="/img/kazan_besi_pompalari.jpg"><br>
                    <p></p>
                </div>
                <div class="col-md-6 mb-1 mt-5-1" style="text-align: justify;">
                    <b style="color: #343a40; font-weight: bold;font-size: 18px;"><?=LH::t("boiler_fattle_pumps")?></b><br>
                    <p style="color: #343a40; font-weight: 600;">
                    <p style="color: #343a40; font-weight: normal;">
                    <?=LH::t("the_boiler_fattening_p_u")?></p></div>
            </div>
            <hr>
            <div class="row mb-5 mt-5">
                <div class="col-md-6 mb-1 mt-5-1">
                    <b style="color: #343a40; font-weight: bold;font-size: 18px;"> <?=LH::t("circulation_pumps")?></b><br>
                    <p style="color: #343a40; font-weight: 600;text-align: justify;">
                    <p style="color: #343a40; font-weight: normal;text-align: justify;">
                    <?=LH::t("the_task_of_t_c")?> </div>
                <div class="col-md-6 mb-1 mt-5-1" style="text-align: right;">
                    <img style="width: 100%" src="/img/sirkülasyon_pompalari.jpg"><br>
                    <p></p>
                    <p></p>
                </div>
            </div>
        </div>

    </section>







    <?php include V_PATH . '/_parts/_footer.phtml'; ?>