<?php


include V_PATH . '/_parts/_head.phtml';
?>
<div role="main" class="main" id="main">

    <section class="section bg-primary border-0 position-relative z-index-1 py-0 m-0 h600">
        <!--2 tane slider var birisi background için diğeri owlcaruosel yazılar için. Background sliderı owlcarousel e bağlı. Reverse olduğu için background resimleri çapraz bağlıdır.-->
        <div class="custom-slider-background overflow-hidden"><!--solcu-->
            <div class="custom-slider-background-image-stage-outer appear-animation" data-appear-animation="maskUp" data-appear-animation-delay="500">
                <div class="custom-slider-background-image-stage">
                    <div class="custom-slider-background-image-item overlay overlay-show overlay-op-6 slide_img_left"></div>
                    <div class="custom-slider-background-image-item overlay overlay-show overlay-op-6 slide_img_left"></div>
                    <div class="custom-slider-background-image-item overlay overlay-show overlay-op-6 slide_img_left"></div>
                </div>
            </div>

            <div class="custom-slider-background-image-stage-outer appear-animation" data-appear-animation="maskUp" data-appear-animation-delay="500">
                <div class="custom-slider-background-image-stage reverse">
                    <div class="custom-slider-background-image-item overlay overlay-show overlay-op-6 slide_img_right"></div>
                    <div class="custom-slider-background-image-item overlay overlay-show overlay-op-6 slide_img_right"></div>
                    <div class="custom-slider-background-image-item overlay overlay-show overlay-op-6 slide_img_right"></div>
                </div>
            </div>
        </div>
        <div class="owl-carousel-wrapper appear-animation h600" data-appear-animation="maskUp" data-appear-animation-delay="500">
            <div id="slider" class="owl-carousel dots-inside dots-horizontal-center show-dots-xs custom-dots-position nav-style-1 nav-inside nav-inside-plus nav-light nav-lg nav-font-size-lg mb-0" data-plugin-options="{'responsive': {'0': {'items': 1, 'dots': true, 'nav': false}, '479': {'items': 1}, '768': {'items': 1}, '979': {'items': 1}, '1199': {'items': 1, 'nav': true, 'navVerticalOffset': '-100px', 'dots': false}}, 'loop': false, 'autoHeight': true, 'margin': 0, 'dots': true, 'dotsVerticalOffset': '-115px', 'nav': false, 'animateIn': 'fadeIn', 'animateOut': 'fadeOut', 'mouseDrag': true, 'touchDrag': true, 'pullDrag': false, 'autoplay': true,  'autoplayTimeout': 7000, 'autoplayHoverPause': true, 'rewind': true}">

                <!-- Carousel Slide 1 -->
                <div class="position-relative overflow-hidden h600">
                    <div class="container container-xl-custom custom-container-style-2 position-relative z-index-3 h-100 pt-5 mt-5 mt-sm-3">
                        <div class="row align-items-center h-100">
                            <div class="col">
                                <div class="overflow-hidden mb-2 mb-sm-1 mb-md-0">
                                    <h1 class="text-color-light font-weight-black line-height-1 text-10 text-md-13 text-lg-15 ls-0 mb-0 appear-animation" data-appear-animation="maskUp"><?= LH::t("technology_with_water_m") ?></h1>
                                </div>
                                <div class="overflow-hidden opacity-8 mb-1">
                                    <h2 class="text-color-light line-height-6 line-height-md-2 text-5 text-md-6 positive-ls-3 mb-0 appear-animation" data-appear-animation="maskUp" data-appear-animation-delay="90"><?= LH::t("we_pass_in_t_s") ?></h2>
                                </div>


                            </div>
                        </div>
                    </div>
                </div>

                <!-- Carousel Slide 2 -->
                <div class="position-relative overflow-hidden h600">
                    <div class="container container-xl-custom custom-container-style-2 position-relative z-index-3 h-100 pt-5 mt-5 mt-sm-3">
                        <div class="row align-items-center justify-content-end h-100">
                            <div class="col text-end">
                                <div class="overflow-hidden mb-2 mb-sm-1 mb-md-0">
                                    <h1 class="text-color-light font-weight-black line-height-1 text-10 text-md-13 text-lg-15 ls-0 mb-0 appear-animation d-none" data-appear-animation="maskUp"><?= LH::t("water_management_efficiency_p") ?></h1>
                                </div>
                                <div class="overflow-hidden opacity-8 mb-1">
                                    <h2 class="text-color-light line-height-6 line-height-md-2 text-5 text-md-7 positive-ls-3 mb-0 appear-animation d-none" data-appear-animation="maskUp" data-appear-animation-delay="250"><?= LH::t("we_measure_and_a_y") ?></h2>
                                </div>

                            </div>
                        </div>
                    </div>
                </div>
                <div class="position-relative overflow-hidden h600">
                    <div class="container container-xl-custom custom-container-style-2 position-relative z-index-3 h-100 pt-5 mt-5 mt-sm-3">
                        <div class="row align-items-center h-100">
                            <div class="col">
                                <div class="overflow-hidden mb-2 mb-sm-1 mb-md-0">
                                    <h1 class="text-color-light font-weight-black line-height-slide text-10 text-md-13 text-lg-15 ls-0 mb-0 appear-animation" data-appear-animation="maskUp"><?= LH::t("watch_the_energy_m") ?></h1>
                                </div>
                                <div class="overflow-hidden opacity-8 mb-1">
                                    <h2 class="text-color-light line-height-6 line-height-md-2 text-5 text-md-6 positive-ls-3 mb-0 appear-animation" data-appear-animation="maskUp" data-appear-animation-delay="90"><?= LH::t("take_a_step_f_w") ?></h2>
                                </div>

                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <div class="position-relative">
        <img src="/img/demos/architecture-2/backgrounds/arch-plan-1.jpg" class="img-fluid position-absolute top-0 right-0" alt="" />
    </div>

    <div class="custom-page-wrapper">
        <section class="section bg-transparent border-0 position-relative py-0 m-0">
            <div class="container container-xl-custom custom-container-style custom-margin-top">
                <div class="row mb-5">
                    <div class="col">
                        <div class="overflow-hidden">
                            <div class="owl-carousel-wrapper position-relative z-index-1 appear-animation" data-appear-animation="maskUp" data-appear-animation-delay="1000" style="height: 373px;">
                                <div class="owl-carousel owl-theme dots-horizontal-center custom-dots-style-1 mb-0" data-plugin-options="{'responsive': {'576': {'items': 1}, '768': {'items': 1}, '992': {'items': 2}, '1200': {'items': 3}}, 'margin': 25, 'loop': true, 'nav': false, 'dots': true, 'autoplay': true, 'autoplayTimeout': 5000}">
                                    <div>
                                        <a href="#" class="text-decoration-none">
                                            <div class="card custom-card-style-1 border-radius-0">
                                                <div class="card-body text-center p-5 mb-4">
                                                    <img width="75" height="75" src="/img/svg/energy_efficiency.svg" alt="" data-icon data-plugin-options="{'onlySVG': true, 'extraClass': 'svg-fill-color-primary mt-3 mb-4 pb-3'}" />
                                                    <h2 class="text-color-dark font-weight-bold line-height-1 text-6-5 mb-3"><?= LH::t("energy_efficiency_consultancy") ?></h2>
                                                    <p class="mb-0"><?= LH::t("we_are_developing_c_s") ?></p>
                                                </div>
                                            </div>
                                        </a>
                                    </div>
                                    <div>
                                        <a href="#" class="text-decoration-none">
                                            <div class="card custom-card-style-1 border-radius-0">
                                                <div class="card-body text-center p-5 mb-4">
                                                    <img width="75" height="75" src="/img/svg/key.svg" alt="" data-icon data-plugin-options="{'onlySVG': true, 'extraClass': 'svg-fill-color-primary mt-3 mb-4 pb-3'}" />
                                                    <h2 class="text-color-dark font-weight-bold line-height-1 text-6-5 mb-3"><?= LH::t("turnkey_project_management") ?></h2>
                                                    <p class="mb-0"><?= LH::t("we_take_responsibility_f_e") ?></p>
                                                </div>
                                            </div>
                                        </a>
                                    </div>
                                    <div>
                                        <a href="#" class="text-decoration-none">
                                            <div class="card custom-card-style-1 border-radius-0">
                                                <div class="card-body text-center p-5 mb-4">
                                                    <img width="75" height="75" src="/img/svg/cost.svg" alt="" data-icon data-plugin-options="{'onlySVG': true, 'extraClass': 'svg-fill-color-primary mt-3 mb-4 pb-3'}" />
                                                    <h2 class="text-color-dark font-weight-bold line-height-1 text-6-5 mb-3"><?= LH::t("zero_cost_investments") ?></h2>
                                                    <p class="mb-0"><?= LH::t("our_unique_business_m_a") ?></p>
                                                </div>
                                            </div>
                                        </a>
                                    </div>
                                    <div>
                                        <a href="#" class="text-decoration-none">
                                            <div class="card custom-card-style-1 border-radius-0">
                                                <div class="card-body text-center p-5 mb-4">
                                                    <img width="75" height="75" src="/img/svg/software.svg" alt="" data-icon data-plugin-options="{'onlySVG': true, 'extraClass': 'svg-fill-color-primary mt-3 mb-4 pb-3'}" />
                                                    <h2 class="text-color-dark font-weight-bold line-height-1 text-6-5 mb-3"><?= LH::t("energy_monitoring_and_m_s") ?></h2>
                                                    <p class="mb-0"><?= LH::t("our_registered_software_e_u") ?></p>
                                                </div>
                                            </div>
                                        </a>
                                    </div>
                                    <div>
                                        <a href="#" class="text-decoration-none">
                                            <div class="card custom-card-style-1 border-radius-0">
                                                <div class="card-body text-center p-5 mb-4">
                                                    <img width="75" height="75" src="/img/svg/remote_manage.svg" alt="" data-icon data-plugin-options="{'onlySVG': true, 'extraClass': 'svg-fill-color-primary mt-3 mb-4 pb-3'}" />
                                                    <h2 class="text-color-dark font-weight-bold line-height-1 text-6-5 mb-3"><?= LH::t("remote_monitoring_and_m") ?></h2>
                                                    <p class="mb-0"><?= LH::t("our_advanced_scada_s_a") ?></p>
                                                </div>
                                            </div>
                                        </a>
                                    </div>
                                    <div>
                                        <a href="#" class="text-decoration-none">
                                            <div class="card custom-card-style-1 border-radius-0">
                                                <div class="card-body text-center p-5 mb-4">
                                                    <img width="75" height="75" src="/img/svg/measurement.svg" alt="" data-icon data-plugin-options="{'onlySVG': true, 'extraClass': 'svg-fill-color-primary mt-3 mb-4 pb-3'}" />
                                                    <h2 class="text-color-dark font-weight-bold line-height-1 text-6-5 mb-3"><?= LH::t("field_devices_for_p_m") ?></h2>
                                                    <p class="mb-0"><?= LH::t("our_state_o") ?>
                                                    </p>
                                                </div>
                                            </div>
                                        </a>
                                    </div>
                                    <div>
                                        <a href="#" class="text-decoration-none">
                                            <div class="card custom-card-style-1 border-radius-0">
                                                <div class="card-body text-center p-5 mb-4">
                                                    <img width="75" height="75" src="/img/svg/co2.svg" alt="" data-icon data-plugin-options="{'onlySVG': true, 'extraClass': 'svg-fill-color-primary mt-3 mb-4 pb-3'}" />
                                                    <h2 class="text-color-dark font-weight-bold line-height-1 text-6-5 mb-1"><?= LH::t("reduced_carbon_emissions") ?></h2>
                                                    <p class="mb-0"><?= LH::t("we_are_determined_t_m") ?></p>
                                                </div>
                                            </div>
                                        </a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                <section class="parallax bg-transparent border-0 " data-plugin-parallax data-plugin-options="{'speed': 1.5, 'scrollableParallax': true, 'scrollableParallaxMinWidth': 991, 'startOffset': 13, 'cssProperty': 'width', 'cssValueStart': 40, 'cssValueEnd': 100, 'cssValueUnit': 'vw'}">
                    <div class="d-flex justify-content-center">
                        <div class="scrollable-parallax-wrapper bg-primary overflow-hidden row justify-content-center p-5">
                            <h3 class="text-transform-none text-color-light font-weight-black line-height-5 text-9 mb-2"><?= LH::t("our_awards") ?></h3>
                            <a href="https://www.surdurulebilirisodulleri.com/" target="_blank">
                                <div style="display: flex; align-items: center;">
                                    <img src="/img/award/sustainable_2024.webp" width=200 style="margin-right: 20px;"/>

                                    <h3 class="text-transform-none text-color-light font-weight-black line-height-5 text-5 mb-2"> Sürdürülebilir Enerji Yönetimi<p class="mb-0 text-3" style=" color: #999;">Pompa Sistemlerinde Verimlilik Uygulamaları Ve Akıllı Enerji Yönetimi (KOBİ)</p>
                                    </h3>
                                </div>
                            </a>
                            <a href="https://www.surdurulebilirisodulleri.com/surdurulebilir-is-odulleri-2023/" target="_blank">
                                <div style="display: flex; align-items: center;">
                                    <img src="/img/award/sustainable_2023.webp" width=200 style="margin-right: 20px;" />
                                    <h3 class="text-transform-none text-color-light font-weight-black line-height-5 text-5 mb-2">Sürdürülebilir İnovasyon - Proses <p class="mb-0 text-3" style=" color: #999;"> Pompa Sistemlerinde Enerji Verimliliği Paylaşımı ve İşletilmesi Projesi (KOBİ)</p>
                                    </h3>
                                </div>
                            </a>
                        </div>
                    </div>
                </section>

                <section class=" parallax bg-transparent border-0 " data-plugin-parallax data-plugin-options="{'speed': 1.5, 'scrollableParallax': true, 'scrollableParallaxMinWidth': 991, 'startOffset': 13, 'cssProperty': 'width', 'cssValueStart': 40, 'cssValueEnd': 100, 'cssValueUnit': 'vw'}">
                    <div class="d-flex justify-content-center">
                        <div class="scrollable-parallax-wrapper bg-primary overflow-hidden">
                            <div class="row justify-content-center p-5">
                                <div class="col-sm">

                                    <div style="display: flex;height: 100%;align-items: center;">
                                        <h3 class="text-transform-none text-color-light font-weight-black line-height-5 text-9 mb-2"><?= LH::t("watch_presentation_video") ?></h3>
                                    </div>
                                </div>
                                <div class="col-sm">
                                    <iframe style="width: 100%;height:30vh;" src="https://www.youtube.com/embed/93j37010LDY" frameborder="0" allowfullscreen data-autoplay></iframe>
                                </div>
                            </div>
                        </div>
                    </div>
                </section>

                <div id="start" class="row align-items-center pb-xl-5 mb-xl-5">
                    <div class="col-9 col-lg-4 col-xl-5 pb-5 pb-lg-0 mb-5 mb-lg-0">
                        <div class="position-relative">
                            <img src="/img/demos/architecture-2/backgrounds/arch-plan-2.jpg" class="img-fluid position-absolute left-0 z-index-0 appear-animation" alt="" data-appear-animation="fadeIn" data-appear-animation-delay="500" style="bottom: -168px;" />
                            <div class="overflow-hidden position-relative z-index-1">
                                <img src="/img/technology-01.jpg" class="img-fluid appear-animation" alt="" data-appear-animation="maskLeft" data-appear-animation-delay="250" />
                            </div>
                            <div class="overflow-hidden position-absolute z-index-2" style="bottom: -75px; right: -17%;">
                                <img src="/img/work_city.jpg" class="img-fluid appear-animation" alt="" data-appear-animation="maskRight" data-appear-animation-delay="550" />
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-7 col-xl-5 offset-lg-1 position-relative pt-5 pt-lg-0">
                        <div class="position-absolute z-index-0 left-0 appear-animation" data-appear-animation="fadeInRightShorter" data-appear-animation-delay="1000" style="top: 190px;">
                            <h2 class="text-color-dark custom-stroke-text-effect-1 custom-big-font-size-1 font-weight-black opacity-1 mb-0"><?= LH::t("energy") ?></h2>
                        </div>
                        <div class="pt-lg-5 ps-lg-5 mt-lg-5">
                            <div class="overflow-hidden mb-2">
                                <h2 class="text-color-default positive-ls-3 line-height-3 text-4 mb-0 appear-animation" data-appear-animation="maskUp" data-appear-animation-delay="400"><?= LH::t("we_are_here_t_h") ?></h2>
                            </div>
                            <div class="overflow-hidden mb-3">
                                <h3 class="text-transform-none text-color-dark font-weight-black text-10 line-height-2 mb-0 appear-animation" data-appear-animation="maskUp" data-appear-animation-delay="1000"><?= LH::t("experience_and_innovation") ?></h3>
                            </div>
                            <div class="appear-animation" data-appear-animation="fadeInUpShorter" data-appear-animation-delay="300">
                                <img src="/img/man_work_city.jpg" class="img-fluid opacity-5 mb-4" alt="" />
                            </div>
                            <p class="custom-font-tertiary text-5 line-height-4 mb-4 appear-animation" data-appear-animation="fadeInUpShorter" data-appear-animation-delay="900"><?= LH::t("we_are_the_l_i") ?></p>
                            <p class="text-3-5 pb-3 mb-4 appear-animation" data-appear-animation="fadeInUpShorter" data-appear-animation-delay="500"><?= LH::t("we_undertake_the_i") ?></p>
                            <a href="/<?= $lang ?>/contact" class="btn btn-primary custom-btn-style-1 font-weight-bold text-3 px-5 py-3 appear-animation" data-appear-animation="fadeInUpShorter" data-appear-animation-delay="500"><?= LH::t("contact_us") ?></a>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <div style="margin-left: 6%;" class="row counters mb-4 ">
            <div class="col-sm-6 col-lg-3 mb-4 mb-lg-5">
                <div class="counter counter-primary">
                    <strong data-to="3472395 " data-append="kWh">0</strong>
                    <label><?= LH::t("managed_electricity") ?></label>
                </div>
            </div>
            <div class="col-sm-6 col-lg-3 mb-4 mb-sm-0 mb-lg-5">
                <div class="counter counter-tertiary">
                    <strong data-to="115" data-append="+">0</strong>
                    <label><?= LH::t("our_facilities") ?></label>
                </div>
            </div>
            <div class="col-sm-6 col-lg-3 mb-lg-5">
                <div class="counter counter-quaternary">
                    <strong data-to="6414133" data-append="m³">0</strong>
                    <label><?= LH::t("managed_water") ?></label>
                </div>
            </div>
        </div>
        <div class="owl-carousel-wrapper position-relative z-index-1 appear-animation" data-appear-animation="maskUp" data-appear-animation-delay="500" style="height: 100%;">

            <div class="featured-boxes featured-boxes-style-8 featured" style="width: 100%;background-image: url(/img/service-5-bg-1-1.jpg);background-repeat: no-repeat">
                <div class="row">
                    <div class="col-lg-6">
                        <div class="featured-box featured-box-primary featured-box-text-start mt-0">
                            <div class="box-content p-5">
                                <div class="row">
                                    <div class="col-9">
                                        <h2 class="font-weight-small text-6"><?= LH::t("our_projects") ?></h2>
                                    </div>
                                    <div class="col-3">
                                        <div class="text-end">
                                            <i class="fa-solid fa-cloud-arrow-down fa-2xl"></i>
                                        </div>
                                    </div>
                                    <div class="col-12">
                                        <h2 class="font-weight-normal text-5"><?= LH::t("predixi_fulf_based_w_c") ?></h2>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col">
                                        <p><?= LH::t("predixi_consists_of_c") ?></p>
                                        <a href="/<?= $lang ?>/predixi-cloud-water-control-software"> <button class="btn btn-modern btn-dark me-1" type="button"><?= LH::t("more") ?></button></a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-6">
                        <div class="featured-box featured-box-primary featured-box-text-start mt-0">
                            <div class="box-content p-5">
                                <div class="row">
                                    <div class="col-9">
                                        <h2 class="font-weight-small text-6"><?= LH::t("our_projects") ?></h2>
                                    </div>
                                    <div class="col-3">
                                        <div class="text-end">
                                            <i class="fa-solid fa-hand-holding-droplet fa-2xl"></i>
                                        </div>
                                    </div>
                                    <div class="col-12">
                                        <h2 class="font-weight-normal text-5"><?= LH::t("metirius_water_control_d") ?></h2>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col">
                                        <p><?= LH::t("they_are_electronic_s") ?>
                                        </p>
                                        <a href="/<?= $lang ?>/metirius-water-management-devices"> <button class="btn btn-modern btn-dark me-1" type="button"><?= LH::t("more") ?></button></a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-lg-6">
                        <div class="featured-box featured-box-primary featured-box-text-start mt-0">
                            <div class="box-content p-5">
                                <div class="row">
                                    <div class="col-9">
                                        <h2 class="font-weight-small text-6"><?= LH::t("our_projects") ?></h2>
                                    </div>
                                    <div class="col-3">
                                        <div class="text-end">
                                            <i class="fa-solid fa-house-flood-water-circle-arrow-right fa-2xl"></i>
                                        </div>
                                    </div>
                                    <div class="col-12">
                                        <h2 class="font-weight-normal text-5"><?= LH::t("metirius_ww_w") ?></h2>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col">
                                        <p><?= LH::t("wastewater_control_systems_h_b") ?></p>
                                        <a href="/<?= $lang ?>/metirius-ww-wastewater-control-system"> <button class="btn btn-modern btn-dark me-1" type="button"><?= LH::t("more") ?></button></a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-6">
                        <div class="featured-box featured-box-primary featured-box-text-start mt-0">
                            <div class="box-content p-5">
                                <div class="row">
                                    <div class="col-9">
                                        <h2 class="font-weight-small text-6"><?= LH::t("our_projects") ?></h2>
                                    </div>
                                    <div class="col-3">
                                        <div class="text-end">
                                            <i class="fa-solid fa-diagram-project fa-2xl"></i>
                                        </div>
                                    </div>
                                    <div class="col-12">
                                        <h2 class="font-weight-normal text-5"><?= LH::t("metirius_network_failure_c_s") ?></h2>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col">
                                        <p><?= LH::t("the_status_of_t_s") ?></p>
                                        <a href="/<?= $lang ?>/metirius-network-mains-control-system"> <button class="btn btn-modern btn-dark me-1" type="button"><?= LH::t("more") ?></button></a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

        </div>
        <section class="section bg-transparent border-0 position-relative m-0">
            <div class="container container-xl-custom py-5">
                <div class="row">
                    <div class="col text-center position-relative">
                        <div class="appear-animation" data-appear-animation="fadeInUpShorter" data-appear-animation-delay="500">

                        </div>
                        <h3 class="text-transform-none text-color-dark font-weight-black text-10 line-height-2 mb-3"><?= LH::t("use_one_linkedin") ?></h3>
                        <img src="/img/demos/architecture-2/divider.jpg" class="img-fluid opacity-5 mt-3 mb-5" alt="" />
                    </div>
                </div>
                <script>
                    function resizeIframe(obj) {
                        obj.style.height = obj.contentWindow.document.documentElement.scrollHeight + 'px';
                    }
                </script>
                <iframe src='https://widgets.sociablekit.com/linkedin-page-posts/iframe/25404892' frameborder="0" scrolling="no" onload="resizeIframe(this)" width='100%' height='600px'></iframe>
            </div>
        </section>
        <section class="section bg-transparent border-0 position-relative m-0">
            <div class="container container-xl-custom py-5">
                <div class="row">
                    <div class="col text-center position-relative">
                        <div class="appear-animation" data-appear-animation="fadeInUpShorter" data-appear-animation-delay="500">
                            <div class="position-absolute transform3dx-n50 left-50pct z-index-0" style="top: 56px;">
                                <h2 class="text-color-dark custom-stroke-text-effect-1 custom-big-font-size-1 font-weight-black opacity-1 mb-0"><?= LH::t("whats_happening") ?></h2>
                            </div>
                        </div>
                        <h2 class="text-color-default positive-ls-3 line-height-3 text-4 mb-2"><?= LH::t("our_blog") ?></h2>
                        <h3 class="text-transform-none text-color-dark font-weight-black text-10 line-height-2 mb-3"><?= LH::t("latest_news") ?></h3>
                        <img src="/img/demos/architecture-2/divider.jpg" class="img-fluid opacity-5 mt-3 mb-5" alt="" />
                    </div>
                </div>
                <div class="row row-gutter-sm">
                    <div class="col-lg-4 mb-4 mb-lg-0">
                        <article>
                            <div class="card border-0 border-radius-0">
                                <div class="card-body bg-color-light-scale-1 p-4 z-index-1">
                                    <img class="card-img-top border-radius-0 hover-effect-2" src="/img/news_photo_1.jpg" alt="Card Image">
                                    </a>
                                    <p class="text-uppercase text-1 mb-3 pt-1 text-color-default">
                                        <time pubdate datetime="2023-01-10">2022</time>
                                        <span class="opacity-3 d-inline-block px-2"> IEA,Paris|</span>
                                        <span class="opacity-3 d-inline-block px-2">|</span>
                                    </p>
                                    <div class="card-body p-0">
                                        <h4 class="card-title mb-3 text-5 font-weight-semibold"><a class="text-color-dark text-color-hover-primary text-decoration-none font-weight-bold text-3-5"><?= LH::t("energy_efficiency_2022") ?></a></h4>
                                        <p class="card-text mb-2"><?= LH::t("energy_efficiency_2022_i_t") ?></p>
                                        <a href="https://www.iea.org/reports/energy-efficiency-2022" target="_blank" class="custom-read-more d-inline-flex align-items-center font-weight-semibold text-3 text-decoration-none ps-0">
                                            <?= LH::t("read_more") ?>
                                        </a>
                                    </div>
                                </div>
                            </div>
                        </article>
                    </div>
                    <div class="col-lg-4 mb-4 mb-lg-0">
                        <article>
                            <div class="card border-0 border-radius-0">
                                <div class="card-body bg-color-light-scale-1 p-4 z-index-1">

                                    <img class="card-img-top border-radius-0 hover-effect-2" src="/img/news_photo_2.jpg" alt="Card Image">
                                    </a>
                                    <p class="text-uppercase text-1 mb-3 pt-1 text-color-default">
                                        <time pubdate datetime="2023-01-10">10 Jan 2023</time>
                                        <span class="opacity-3 d-inline-block px-2">|</span>
                                        <span class="opacity-3 d-inline-block px-2">|</span>
                                    </p>
                                    <div class="card-body p-0">
                                        <h4 class="card-title mb-3 text-5 font-weight-semibold"><a class="text-color-dark text-color-hover-primary text-decoration-none font-weight-bold text-3-5">Energy efficiency, combating climate change tool</a></h4>
                                        <p class="card-text mb-2"><?= LH::t("the_concept_of_e_e") ?></p>
                                        <a href="https://www.telefonica.com/en/communication-room/energy-efficiency-is-one-of-the-tools-available-to-society-to-combat-climate-change-the-greatest-challenge-facing-humankind-today/" target="_blank" class="custom-read-more d-inline-flex align-items-center font-weight-semibold text-3 text-decoration-none ps-0">
                                            <?= LH::t("read_more") ?>
                                        </a>
                                    </div>
                                </div>
                            </div>
                        </article>
                    </div>
                    <div class="col-lg-4 mb-4 mb-lg-0">
                        <article>
                            <div class="card border-0 border-radius-0">
                                <div class="card-body bg-color-light-scale-1 p-4 z-index-1">

                                    <img class="card-img-top border-radius-0 hover-effect-2" src="/img/news_photo_3.png" alt="Card Image">
                                    </a>
                                    <p class="text-uppercase text-1 mb-3 pt-1 text-color-default">
                                        <time pubdate datetime="2023-01-10">10 Jan 2023</time>
                                        <span class="opacity-3 d-inline-block px-2">|</span>
                                        <span class="opacity-3 d-inline-block px-2">|</span>
                                    </p>
                                    <div class="card-body p-0">
                                        <h4 class="card-title mb-3 text-5 font-weight-semibold"><a class="text-color-dark text-color-hover-primary text-decoration-none font-weight-bold text-3-5">2022 Climate Status Services: Energy</a></h4>
                                        <p class="card-text mb-2"><?= LH::t("geneva_11_october_2") ?></p>
                                        <a href="https://reliefweb.int/report/world/2022-state-climate-services-energy" target="_blank" class="custom-read-more d-inline-flex align-items-center font-weight-semibold text-3 text-decoration-none ps-0">
                                            <?= LH::t("read_more") ?>
                                        </a>
                                    </div>
                                </div>
                            </div>
                        </article>
                    </div>
                </div>
            </div>
        </section>

        <!-- <section class="section section-height-3 bg-primary border-0 m-1">
            <div class="container container-xl-custom">
                <div class="row align-items-center justify-content-center text-center text-xl-start">
                    <div class="col-md-8 col-xl-9 mb-4 mb-xl-0 appear-animation" data-appear-animation="fadeInRightShorterPlus" data-appear-animation-delay="250">
                        <h2 class="text-color-default font-weight-semibold positive-ls-3 text-4 mb-0"><?= LH::t("we_are_here_t_h") ?></h2>
                        <h3 class="text-transform-none text-color-light font-weight-black line-height-2 text-9 mb-0"><?= LH::t("lets_talk_about_y_n") ?></h3>
                    </div>
                    <div class="col-xl-3 text-xl-end appear-animation" data-appear-animation="fadeInRightShorterPlus" data-appear-animation-delay="500">
                        <a href="/tr/contact" class="btn btn-light custom-btn-style-1 font-weight-bold text-color-dark text-3 px-5 py-3"><?= LH::t("contact_us") ?></a>
                    </div>
                </div>
            </div>
        </section> -->

        <!-- <section class="section parallax bg-transparent border-0  mt-2 " data-plugin-parallax data-plugin-options="{'speed': 1.5, 'scrollableParallax': true, 'scrollableParallaxMinWidth': 991, 'startOffset': 13, 'cssProperty': 'width', 'cssValueStart': 40, 'cssValueEnd': 100, 'cssValueUnit': 'vw'}">
            <div class="d-flex justify-content-center">
                <div class="scrollable-parallax-wrapper bg-primary overflow-hidden">
                    <div class="container container-xl-custom custom-container-style-3 custom-container-position-1 py-5 my-5 mx-0">
                        <div class="row justify-content-center pt-3 mb-5">
                            <div class="col-sm-8 col-md-12 text-center">


                            </div>
                        </div>
                        <div class="row justify-content-center pb-3">
                            <div class="col-lg-9">
                                <div class="owl-carousel owl-theme nav-style-1 nav-light nav-outside nav-font-size-lg custom-dots-style-1 custom-dots-style-1-light mb-0" data-plugin-options="{'responsive': {'0': {'items': 1, 'nav': false, 'dots': true}, '576': {'items': 1, 'nav': false, 'dots': true}, '768': {'items': 1, 'nav': false, 'dots': true}, '992': {'items': 1}, '1200': {'items': 1}}, 'loop': false, 'nav': true, 'dots': false}">
                                    <div>
                                        <div class="testimonial testimonial-style-2 testimonial-with-quotes testimonial-remove-right-quote custom-testimonial-quote mb-0">
                                            <blockquote>
                                                <p class="custom-font-secondary text-color-light opacity-8 font-weight-light line-height-6 text-4-5 px-2 px-lg-3 mb-0"><em><?= LH::t("the_energy_makes_i_e") ?></em></p>
                                            </blockquote>
                                            <div class="testimonial-author">
                                                <p class="text-color-light font-weight-bold text-4 mb-0">Lao Tzu</p>
                                            </div>
                                        </div>
                                    </div>
                                    <div>
                                        <div class="testimonial testimonial-style-2 testimonial-with-quotes testimonial-remove-right-quote custom-testimonial-quote mb-0">
                                            <blockquote>
                                                <p class="custom-font-secondary text-color-light opacity-8 font-weight-light line-height-6 text-4-5 px-2 px-lg-3 mb-0"><em><?= LH::t("productivity_is_never_r_a") ?></p>
                                            </blockquote>
                                            <div class="testimonial-author">
                                                <p class="text-color-light font-weight-bold text-4 mb-0">Paul J. Meyer</p>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section> -->

    </div>



</div>
<?php
include V_PATH . '/_parts/_footer.phtml';
?>