<?php include V_PATH . '/_parts/_head.phtml'; ?>
<div role="main" class="main">
    <?php
    $pageTitle = "KVKK Information";
    include V_PATH . '/_parts/title.phtml';
    ?>

    <style>
        .row mb-2 strong {
            font-size: 25px;
            ;
        }

        .metin a {
            color: black;
            font-weight: bold;
        }

        .metin a:hover {
            text-decoration: underline;
        }
    </style>
    <section class="ls section_padding_top_50 section_padding_bottom_100">
        <div class="container" style="margin-top: 10;
    padding: 0;
    padding-top: 120px;">


            <div class="metin" style="margin-bottom: 22px;margin-left: 0.5%;margin-right: 0.5%;color: #000000e0;font-weight: bolder; background-color: #eeeeeee8; padding: 3%;">
                <div class="row">

                  <strong><?=LH::t("information_about_the_p_a")?></strong>
                    <p><?=LH::t("solid_electron_control_t_i")?></p>
                    <strong><?=LH::t("collection_processing_a")?></strong>
                    <p><?=LH::t("your_personal_data_m_v")?></p>
                    <p><?=LH::t("the_collected_personal_d_w")?></p>

                    <strong><?=LH::t("recipients_and_purposes_o_t")?></strong>
                    <p><?=LH::t("the_collected_personal_d_m")?></p>

                    <strong><?=LH::t("method_and_legal_b_o")?></strong>
                    <p><?=LH::t("your_personal_data_i_o")?></p>

                    <strong><?=LH::t("rights_of_the_d_s")?></strong>
                    <p><?=LH::t("as_data_subjects_i")?></p>
                    <p><?=LH::t("in_this_context_d")?></p>
                    <ul>
                        <li><?=LH::t("to_learn_whether_p_d")?></li>
                        <li><?=LH::t("to_request_information_i_p")?></li>
                        <li><?=LH::t("to_learn_the_p_o")?></li>
                        <li><?=LH::t("to_know_the_t_p")?></li>
                        <li><?=LH::t("to_request_the_c_o")?></li>
                        <li><?=LH::t("to_request_the_d_o")?></li>
                        <li><?=LH::t("to_object_to_t_e")?></li>
                        <li><?=LH::t("to_demand_compensation_i_h")?></li>
                    </ul>
                    <p><?=LH::t("in_accordance_with_a_1")?></p>
                    <p><?=LH::t("to_use_your_a_r")?></p>
                    <ul>
                        <li><a target="_blank" href="https://solid.kvksis.com/">solid.kvksis.com</a> <?=LH::t("you_can_send_i_f")?></li>
                    </ul>
                    <div class="swp-hidden-panel-wrap" style="display: none; visibility: collapse; opacity: 0">
                        <div class="swp_social_panel swp_horizontal_panel swp_flat_fresh  swp_default_full_color swp_individual_full_color swp_other_full_color scale-100  scale-" data-min-width="1100" data-float-color="#ffffff" data-float="none" data-float-mobile="none" data-transition="slide" data-post-id="7674">
                            <div class="nc_tweetContainer swp_share_button swp_twitter" data-network="twitter"><a class="nc_tweet swp_share_link" rel="nofollow noreferrer noopener" target="_blank" href="https://twitter.com/intent/tweet?text=KVK+Bilgilendirme+Metni&amp;url=https%3A%2F%2Fsofttech.com.tr%2Fkvkk-bilgilendirme-metni%2F" data-link="https://twitter.com/intent/tweet?text=KVK+Bilgilendirme+Metni&amp;url=https%3A%2F%2Fsofttech.com.tr%2Fkvkk-bilgilendirme-metni%2F"><span class="swp_count swp_hide"><span class="iconFiller"><span class="spaceManWilly"><i class="sw swp_twitter_icon"></i><span class="swp_share"><?=LH::t("tweet")?></span></span></span></span></a></div>
                            <div class="nc_tweetContainer swp_share_button swp_linkedin" data-network="linkedin"><a class="nc_tweet swp_share_link" rel="nofollow noreferrer noopener" target="_blank" href="https://www.linkedin.com/company/solid-electron/cws/share?url=https%3A%2F%2Fsofttech.com.tr%2Fkvkk-bilgilendirme-metni%2F" data-link="https://www.linkedin.com/company/solid-electron/cws/share?url=https%3A%2F%2Fsofttech.com.tr%2Fkvkk-bilgilendirme-metni%2F"><span class="swp_count swp_hide"><span class="iconFiller"><span class="spaceManWilly"><i class="sw swp_linkedin_icon"></i><span class="swp_share"><?=LH::t("share")?></span></span></span></span></a></div>
                            <div class="nc_tweetContainer swp_share_button swp_facebook" data-network="facebook"><a class="nc_tweet swp_share_link" rel="nofollow noreferrer noopener" target="_blank" href="https://www.facebook.com/share.php?u=https%3A%2F%2Fsofttech.com.tr%2Fkvkk-bilgilendirme-metni%2F" data-link="https://www.facebook.com/share.php?u=https%3A%2F%2Fsofttech.com.tr%2Fkvkk-bilgilendirme-metni%2F"><span class="swp_count swp_hide"><span class="iconFiller"><span class="spaceManWilly"><i class="sw swp_facebook_icon"></i><span class="swp_share">Share</span></span></span></span></a></div>
                        </div>
                    </div>
                    <div class="swp-content-locator"></div>
                </div>


            </div>
        </div>
    </section>




    <?php include V_PATH . '/_parts/_footer.phtml'; ?>