<?php include V_PATH . '/_parts/_head.phtml'; ?>
<div role="main" class="main">
    <?php
    $pageTitle = "Logos";
    include V_PATH . '/_parts/title.phtml';
    ?>
    <section class="ls section_padding_top_50 section_padding_bottom_100">
        <div class="container" id="cont_id" style="margin-top:150px;">
            <div class="jumbotron p-1 p-md-1 bg-white text-center">

                <p></p>
                <hr>
                <p style="color: #343a40; font-weight: bolder;">
                   <?=LH::t("you_need_to_u_d")?> </p>
                </p>
            </div>
            <div class="box">
                <div class="container">
                    <div class="row">
                        <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12" style="margin-bottom: 15px;">

                            <div class="card border-secondary mb-3" style="max-width: 540px;padding: 12px;margin: 8px; height: 118px;">
                                <div class="row no-gutters">
                                    <div class="col-md-4" style="margin-top: 0;">
                                        <div class="card-body" style="padding: 0px;">
                                            <div class="downDropdown">
                                                <button class="downBtn"><img class="down" src="/img/logos/button/download.png"></button>
                                                <div class="downDropdown-content">
                                                    <a download href="/img/logos/SVG/SolidElectron.svg"><img class="format" width="30" src="/img/logos/button/svg.png">&nbsp;</a>
                                                    <a download href="/img/logos/PDF/SolidElectron.pdf"><img class="format" width="30" src="/img/logos/button/pdf.png">&nbsp;</a>
                                                    <a download href="/img/logos/PNG/SolidElectron.png"><img class="format" width="30" src="/img/logos/button/png.png">&nbsp;</a>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-md-8">
                                        <img style="width: 170px;object-fit: contain;" src="/img/logos/solidelectron.png" class="card-img-logo" alt="...">
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12" style="margin-bottom: 15px;">

                            <div class="card border-secondary mb-3" style="max-width: 540px;padding: 12px;margin: 8px;height: 118px;">
                                <div class="row no-gutters">
                                    <div class="col-md-4" style="margin-top: 0;">
                                        <div class="card-body" style="padding: 0px;">
                                            <div class="downDropdown">
                                                <button class="downBtn"><img class="down" src="/img/logos/button/download.png"></button>
                                                <div class="downDropdown-content">
                                                    <a download href="/img/logos/SVG/Metirius.svg"><img class="format" width="30" src="/img/logos/button/svg.png">&nbsp;</a>
                                                    <a download href="/img/logos/PDF/Metirius.pdf"><img class="format" width="30" src="/img/logos/button/pdf.png">&nbsp;</a>
                                                    <a download href="/img/logos/PNG/Metirius.png"><img class="format" width="30" src="/img/logos/button/png.png">&nbsp;</a>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-md-8">
                                        <img style="width: 170px;object-fit: contain;" src="/img/logos/metirius.png" class="card-img-logo" alt="...">
                                    </div>
                                </div>
                            </div>
                        </div>


                        <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12" style="margin-bottom: 15px;">
                            <div class="card border-secondary mb-3" style="max-width: 540px;padding: 12px;margin: 8px;height: 118px;">
                                <div class="row no-gutters">
                                    <div class="col-md-4" style="margin-top: 0;">
                                        <div class="card-body" style="padding: 0px;">
                                            <div class="downDropdown">
                                                <button class="downBtn"><img class="down" src="/img/logos/button/download.png"></button>
                                                <div class="downDropdown-content">
                                                    <a download href="/img/logos/SVG/Predixi.svg"><img class="format" width="30" src="/img/logos/button/svg.png">&nbsp;</a>
                                                    <a download href="/img/logos/PDF/Predixi.pdf"><img class="format" width="30" src="/img/logos/button/pdf.png">&nbsp;</a>
                                                    <a download href="/img/logos/PNG/Predixi.png"><img class="format" width="30" src="/img/logos/button/png.png">&nbsp;</a>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-md-8">
                                        <img  style="width: 170px;object-fit: contain;" src="/img/logos/predixi.png" class="card-img-logo" alt="...">
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12" style="margin-bottom: 15px;">
                            <div class="card border-secondary mb-3" style="max-width: 540px;padding: 12px;margin: 8px;height: 118px;">
                                <div class="row no-gutters">
                                    <div class="col-md-4" style="margin-top: 0;">
                                        <div class="card-body" style="padding: 0px;">
                                            <div class="downDropdown">
                                                <button class="downBtn"><img class="down" src="/img/logos/button/download.png"></button>
                                                <div class="downDropdown-content">
                                                    <a download href="/img/logos/SVG/aquaguidblack.svg"><img class="format" width="30" src="/img/logos/button/svg.png">&nbsp;</a>
                                                    <a download href="/img/logos/PDF/aqua_guide.pdf"><img class="format" width="30" src="/img/logos/button/pdf.png">&nbsp;</a>
                                                    <a download href="/img/logos/PNG/aqua_guide.png"><img class="format" width="30" src="/img/logos/button/png.png">&nbsp;</a>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-md-8">
                                        <img  style="width: 170px;object-fit: contain;" src="/img/logos/aqua_guide.png" class="card-img-logo" alt="...">
                                    </div>
                                </div>
                            </div>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </section>

    <?php include V_PATH . '/_parts/_footer.phtml'; ?>