<?php
include V_PATH . '/_parts/_head.phtml';
?>

<?php
$pageTitle = "Metirius Limit Flow Control System";
include V_PATH . '/_parts/title.phtml';
?>

<section class="ls section_padding_top_50 section_padding_bottom_100">
    <div class="container" id="cont_id" style="margin-top:120px;">
        <div class="jumbotron p-1 p-md-1 bg-white">
            <div class="row" style="color: #f5bb2c;font-weight: normal;background-color: #f7f7f7;">
                <div class="col-md-6">
                    <h2 class="display-4 "style="color:
									black;
									font-size: 35px;
									font-weight: bold;
									background-color:
									#f7f7f7;
									padding: 40px;
										padding-top: 40px;
										padding-bottom: 40px;
									border: 6px;
									padding-top: 60px;
									padding-bottom: 10px;"><?= LH::t("the_operation_of_t_s") ?></h2>
                </div>
                <div class="col-md-6" style="background-color: #f7f7f7;">

                </div>
                <div class="col-md-6 bg-white" style="height: 70px;">
                </div>
                <div class="col-md-6" style="background-color: #fff;height: 70px;padding-top:1.2%;">
                    <div class="" style="width:50%;height: 70px;margin-left: auto;">
                        <a style="color: #bb7900; font-weight: bold;" href="/s/dl/metirius_limit_akis_kontrol.pdf" target="_blank"><img style="width:13%;" src="/img/pdf_icon_download.svg"><a style="color: #bb7900; font-weight: bold;" href="/s/dl/metirius_limit_akis_kontrol.pdf" target="_blank" target="_blank">&nbsp<?= LH::t("metirius_limit_flow_c_s") ?></a></i>
                    </div>
                </div>
            </div>
        </div>

        <div class="jumbotron p-1 p-md-1 bg-white" style="margin-top: -2%;">
            <img src="\img\sistemin_isleyisi.png" alt="" style="width:100%">
        </div>
        <div class="jumbotron p-1 p-md-1 bg-white" style="text-align: justify;">
            <p style="color: #343a40;font-size: 17px; font-weight: normal;">
            <p> <?= LH::t("pcp_and_fcv_m_d") ?>
      </p>
        </div>
        <div class="jumbotron p-1 p-md-1 bg-white">
            <div class="row mb-2" style="color: #f5bb2c;font-weight: normal;background-color: #f7f7f7;">
                <div class="col-md-6">
                    <h2 class="display-4 " style="color:
									black;
									font-size: 35px;
									font-weight: bold;
									background-color:
									#f7f7f7;
									padding: 40px;
										padding-top: 40px;
										padding-bottom: 40px;
									border: 6px;
									padding-top: 60px;
									padding-bottom: 10px;"><?= LH::t("fcv_room") ?></h2>
                </div>
                <div class="col-md-6" style="background-color: #f7f7f7;">

                </div>
                <div class="col-md-6 bg-white" style="height: 70px;">
                </div>
                <div class="col-md-6" style="background-color: #fff;height: 70px;padding-top:1.8%;">
                    <div class="right-block float-right" style="width:50%;height: 70px;margin-left: auto;">
                        <a style="color: #bb7900; font-weight: bold;" href="/s/dl/metirius_limit_akis_kontrol.pdf" target="_blank"><img style="width:13%;" src="/img/pdf_icon_download.svg"><a style="color: #bb7900; font-weight: bold;" href="/s/dl/metirius_limit_akis_kontrol.pdf" target="_blank">&nbspMetirius Limit Flow Control System</a></i>
                    </div>
                </div>
            </div>
        </div>
        <div class="jumbotron p-1 p-md-1 bg-white" style="margin-top: -2%;">
            <img src="\img\fcv_odasi.png" alt="" style="width:100%">
        </div>
        <div class="jumbotron p-1 p-md-1 bg-white" style="text-align: justify;">
            <p></p>
            <p style="color: #343a40;font-size: 17px; font-weight: normal;">
            <?= LH::t("fcv_rooms_are_i_a") ?>
        </div>
        <div class="jumbotron p-1 p-md-1 bg-white">
            <div class="row mb-2" style="color: #343a40;font-weight: normal;background-color: #f7f7f7;">
                <div class="col-md-6">
                    <h2 class="display-4 " style="color:
									black;
									font-size: 35px;
									font-weight: bold;
									background-color:
									#f7f7f7;
									padding: 40px;
										padding-top: 40px;
										padding-bottom: 40px;
									border: 6px;
									padding-top: 60px;
									padding-bottom: 10px;">            <?= LH::t("pcp_room") ?>
</h2>
                </div>
                <div class="col-md-6" style="background-color: #f7f7f7;">

                </div>
                <div class="col-md-6 bg-white" style="height: 70px;">
                </div>
                <div class="col-md-6" style="background-color: #fff;height: 70px;padding-top:1.8%;">
                    <div class="right-block float-right" style="width:50%;height: 70px;margin-left: auto;">
                        <a style="color: #bb7900; font-weight: bold;" href="/s/dl/metirius_limit_akis_kontrol.pdf" target="_blank"><img style="width:13%;" src="/img/pdf_icon_download.svg"><a style="color: #bb7900; font-weight: bold;" href="/s/dl/metirius_limit_akis_kontrol.pdf" target="_blank"> <?= LH::t("metirius_limit_flow_c_s") ?></a></i>
                    </div>
                </div>
            </div>
        </div>
        <div class="jumbotron p-1 p-md-1 bg-white" style="margin-top: -2%;">
            <img src="\img\pcp_odasi.png" alt="" style="width:100%">
        </div>
        <div class="jumbotron p-1 p-md-1 bg-white" style="text-align: justify;">
            <p></p>
            <p style="color: #343a40;font-size: 17px; font-weight: normal;">
            <?= LH::t("pcp_rooms_are_i_a") ?>
        </div>
        <div class="jumbotron p-1 p-md-1 bg-white">
            <div class="row mb-2" style="color: #f5bb2c;font-weight: normal;background-color: #f7f7f7;">
                <div class="col-md-6">
                    <h2 class="display-4 " style="color:
									black;
									font-size: 35px;
									font-weight: bold;
									background-color:
									#f7f7f7;
									padding: 40px;
										padding-top: 40px;
										padding-bottom: 40px;
									border: 6px;
									padding-top: 60px;
									padding-bottom: 10px;"> <?= LH::t("scheduled_work") ?></h2>
                </div>
                <div class="col-md-6" style="background-color: #f7f7f7;">

                </div>
                <div class="col-md-6 bg-white" style="height: 70px;">
                </div>
                <div class="col-md-6" style="background-color: #fff;height: 70px;padding-top:1.8%;">
                    <div class="right-block float-right" style="width:50%;height: 70px;margin-left: auto;">
                        <a style="color: #bb7900; font-weight: bold;" href="/s/dl/metirius_limit_akis_kontrol.pdf" target="_blank"><img style="width:13%;" src="/img/pdf_icon_download.svg"><a style="color: #bb7900; font-weight: bold;" href="/s/dl/metirius_limit_akis_kontrol.pdf" target="_blank"><?= LH::t("metirius_limit_flow_c_s") ?></a></i>
                    </div>
                </div>
            </div>
        </div>
        <div class="jumbotron p-1 p-md-1 bg-white" style="margin-top: -2%;">
            <img src="\img\programli_calisma.png" alt="" style="width:100%">
        </div>
        <div class="jumbotron p-1 p-md-1 bg-white" style="text-align: justify;">
            <p></p>
            <p style="color: #343a40;font-size: 17px; font-weight: normal;">
            <?= LH::t("to_the_amount_o_f") ?>
        </div>
        <div class="jumbotron p-1 p-md-1 bg-white">
            <div class="row mb-2" style="color: #f5bb2c;font-weight: normal;background-color: #f7f7f7;">
                <div class="col-md-6">
                    <h2 class="display-4 " style="color:
									black;
									font-size: 35px;
									font-weight: bold;
									background-color:
									#f7f7f7;
									padding: 40px;
										padding-top: 40px;
										padding-bottom: 40px;
									border: 6px;
									padding-top: 60px;
									padding-bottom: 10px;"> <?= LH::t("daily_water_consumption") ?></h2>
                </div>
                <div class="col-md-6" style="background-color: #f7f7f7;">

                </div>
                <div class="col-md-6 bg-white" style="height: 70px;">
                </div>
                <div class="col-md-6" style="background-color: #fff;height: 70px;padding-top:1.8%;">
                    <div class="right-block float-right" style="width:50%;height: 70px;margin-left: auto;">
                        <a style="color: #bb7900; font-weight: bold;" href="/s/dl/metirius_limit_akis_kontrol.pdf" target="_blank"><img style="width:13%;" src="/img/pdf_icon_download.svg"><a style="color: #bb7900; font-weight: bold;" href="/s/dl/metirius_limit_akis_kontrol.pdf" target="_blank"><?= LH::t("metirius_limit_flow_c_s") ?></a></i>
                    </div>
                </div>
            </div>
        </div>
        <div class="jumbotron p-1 p-md-1 bg-white" style="margin-top: -2%;">
            <img src="\img\gunluk_su_tuketim_1.png" alt="" style="width:100%">
        </div>
        <div class="jumbotron p-1 p-md-1 bg-white" style="text-align: justify;">
            <p></p>
            <p style="color: #343a40;font-size: 17px; font-weight: normal;">
            <?= LH::t("the_water_need_g_o") ?>
        </div>
        <div class="jumbotron p-1 p-md-1 bg-white">
            <div class="row mb-2" style="color: #f5bb2c;font-weight: normal;background-color: #f7f7f7;">
                <div class="col-md-7">
                    <h2 class="display-4 " style="color:
									black;
									font-size: 35px;
									font-weight: bold;
									background-color:
									#f7f7f7;
									padding: 40px;
										padding-top: 40px;
										padding-bottom: 40px;
									border: 6px;
									padding-top: 60px;
									padding-bottom: 10px;"> <?= LH::t("daily_water_consumption") ?></h2>
                </div>
                <div class="col-md-5" style="background-color: #f7f7f7;">

                </div>
                <div class="col-md-7 bg-white" style="height: 70px;">
                </div>
                <div class="col-md-5" style="background-color: #fff;height: 70px;padding-top:1.8%;">
                    <div class="right-block float-right" style="width: 60%;height: 70px;margin-left: auto;">
                        <a style="color: #bb7900; font-weight: bold;" href="/s/dl/metirius_limit_akis_kontrol.pdf" target="_blank"><img style="width:13%;" src="/img/pdf_icon_download.svg"><a style="color: #bb7900; font-weight: bold;" href="/s/dl/metirius_limit_akis_kontrol.pdf" target="_blank"><?= LH::t("metirius_limit_flow_c_s") ?></a></i>
                    </div>
                </div>
            </div>
        </div>
        <div class="jumbotron p-1 p-md-1 bg-white" style="margin-top: -2%;">
            <img src="\img\gunluk_su_tuketim_hedeflenen.png" alt="" style="width:100%">
        </div>
        <div class="jumbotron p-1 p-md-1 bg-white" style="text-align: justify;">
            <p></p>
            <p style="color: #343a40;font-size: 17px; font-weight: normal;">
            <?= LH::t("in_our_system_o") ?>
        </div>
    </div>
</section>

<?php include V_PATH . '/_parts/_footer.phtml'; ?>