<?php include V_PATH . '/_parts/_head.phtml'; ?>
<div role="main" class="main">
    <?php
    $pageTitle = "Metirius water control devices";
    include V_PATH . '/_parts/title.phtml';
    ?>




    <section class="ls section_padding_top_50 section_padding_bottom_100">
        <div class="container" style="margin-top:150px; color: #343a40;">
            <img style="width: 200px;" src="/img/logos/metirius.png"><br>
            <p></p>
            <div class="jumbotron p-1 p-md-1 bg-white">
                <h2 class="display-4" style="color: #605e5e;font-weight:600;font-size:27px;">
                <?=LH::t("water_contents")?></h2><br>
                <p style="color: #343a40;">
                <?=LH::t("metirius_are_electronic_s")?> 
                </p>
            </div>
            <div class="row">

                <div class="col-md-6" style="color: #343a40;font-weight: normal;">
                    <ol class="list list-ordened">
                    <li><?=LH::t("pump_base_p")?></li>
                        <li><?=LH::t("pump_ex_p")?> </li>
                        <li><?=LH::t("metirius_tank_base")?></li>
                        <li><?=LH::t("metirius_tank_ex")?></li>
                        <li> <?=LH::t("metirius_waste_base")?></li>
                        <li> <?=LH::t("metirius_waste_ex")?> </li>
                    </ol>
                </div>
                <div class="col-md-3">
                    <img style="height: 300px;" src="/img/predixi/metirius.jpg">
                </div>
            </div>
            <div class="row mb-2">
                <div class="col-md-8 mt-3" style="color: #343a40;font-weight: normal;text-align:justify;">
                <?=LH::t("it_consists_of_a_p")?> 
                </div>
            </div>
       
            <div class="row mb-2 mt-5">
                <div class="col-md-6" style="color: #343a40;font-weight: normal;">
                    <h2 style="color: #605e5e;font-weight:600;font-size:27px;"> <?=LH::t("metirius_communication_devices")?></h2>
                    <ol class="list list-ordened">
                        <li> <?=LH::t("metirius_rf_100_l_d")?></li>
                        <li> <?=LH::t("metirius_rf_101_l_d")?></li>
                    </ol>
                </div>
            </div>
        </div>
    </section>



    <?php include V_PATH . '/_parts/_footer.phtml'; ?>