<?php include V_PATH . '/_parts/_head.phtml'; ?>
<div role="main" class="main">
    <?php
    $pageTitle = "Solid Electron Tekno. Kullanım Şartları";
    include V_PATH . '/_parts/title.phtml';
    ?>
    <section class="ls ms section_padding_100">
        <div class="container" id="cont_id" style="padding-top:150px !important;">
            <div class="row">
                <div class="col-sm-12 to_animate animated fadeInUp">

                    <h3> <?=LH::t("1_conditions")?> </h3>
                    <p><?=LH::t("with_mobile_and_d_a")?> <a id="terms_services_link" href="http://predixi.com"><?=LH::t("http_predixicom")?></a> </p> <p><?=LH::t("aby_accessing_the_w_i")?></p>
                    <h3><?=LH::t("2_use_license")?></h3>
                    <ol type="a">
                        <li><?=LH::t("solid_electron_techns_w_i")?>
                            <ol type="i">
                                <li> <?=LH::t("replace_or_copy_m")?></li>
                                <li> <?=LH::t("use_materials_for_a_c")?></li>
                                <li> <?=LH::t("solid_electron_techtry_t_c")?></li>
                                <li> <?=LH::t("remove_copyright_or_o_r")?> </li>
                                <li> <?=LH::t("transfer_the_materials_t_a")?></li>
                            </ol>
                        </li>
                        <li><?=LH::t("if_you_violate_a_o")?></li>
                    </ol>
                    <h3><?=LH::t("3_legal_warning")?> </h3>
                    <ol type="a">
                        <li> <?=LH::t("solid_electron_techsolid_e_i")?>
                        <li> <?=LH::t("also_solid_e_t")?></li>
                    </ol>
                    <h3>  <?=LH::t("4_limitations")?></h3>
                    <p> <?=LH::t("in_no_case_s")?></p>
                    <h3> <?=LH::t("5_the_accuracy_o_t")?></h3>
                    <p> <?=LH::t("solid_electron_techs_w_m")?></p>
                    <h3><?=LH::t("6_connections")?> </h3>
                    <p> <?=LH::t("solid_electron_is_s_n")?></p>
                    <h3><?=LH::t("7_changes")?> </h3>
                    <p><?=LH::t("solid_electron_is_s_c")?> </p>
                    <h3> <?=LH::t("8_current_law")?> </h3>
                        <p> <?=LH::t("these_provisions_and_c_y")?> </p>
                </div>
            </div>
        </div>
    </section>
    <?php include V_PATH . '/_parts/_footer.phtml'; ?>