<?php include V_PATH . '/_parts/_head.phtml'; ?>
<div role="main" class="main">
	<?php
	$pageTitle = "Water management";
	include V_PATH . '/_parts/title.phtml';
	?>


	<section class="ls section_padding_top_50 section_padding_bottom_15">
		<div class="container" id="cont_id" style="margin-top:150px;">
			<div class="jumbotron p-1 p-md-1 bg-white mb-1" style="text-align:justify;">
				<h2 class="display-4 " style="color: #605e5e;font-weight:600;font-size:27px;">

				<?=LH::t("municipal_and_water_a_s")?></h2>
				<p></p>
				<p style="color: #343a40; font-weight: normal;">
				<?=LH::t("we_produce_technologies_a_a")?>

				<p style="color: #343a40; font-weight: normal;">
				<?=LH::t("we_have_advanced_s_a")?>
			</p>
				</p>
			</div>
			<div class="col-md-12">
				<img src="/img/predixi/su_yonetimi.png">
			</div>
		</div>
</div>
<hr>
<div class="container" id="cont_id">
	<div class="row mb-5 mt-5">
		<div class="col-md-6 mb-1" style="text-align:justify;">
			<b style="color: #605e5e;font-weight:600;font-size:27px;"><?=LH::t("water_cooperative")?></b><br>
			<p></p>
			<p class=" appear-animation" data-appear-animation="fadeInUpShorter" data-appear-animation-delay="400" style="color: #343a40; font-weight: normal;">
			<?=LH::t("we_operate_or_o_t")?>
			</p>

		</div>
		<div class="col-md-6 " style="text-align: justify;">
			<img src="/img/smart_water_system.jpg"><br>
			<p></p>
		</div>
	</div>
</div>

<hr>
<div class="container" id="cont_id" style="padding-top:0.1%;margin-bottom: 4%;">
	<div class="row mb-5 mt-5">
		<div class="col-md-6">
			<img src="/img/tarim_ve_ciftci.jpg"style="width: 100%"><br>
			<p></p>
		</div>
		<div class="col-md-6 mt-1" style="text-align:justify;">
			<b style="color: #605e5e;font-weight:600;font-size:27px;"><?=LH::t("agricultural_companies_and_f")?>
</b><br>
			<p></p>
			<p class=" appear-animation" data-appear-animation="fadeInUpShorter" data-appear-animation-delay="400" style="color: #343a40; font-weight: normal;">
			<?=LH::t("in_order_to_f_t")?>
			</p>
		</div>
	</div>
</div>
</section>





<?php include V_PATH . '/_parts/_footer.phtml'; ?>