<?php
?>
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><?= $pageTitle ?></title>
    <link rel="stylesheet" href="/langs/style.css">
    <link rel="stylesheet" href="/vendor/fontawesome-free/css/all.min.css">
</head>

<body>
    <div class="main-container">
        <div class="menu-container" style="display: block;">
            <h3>Dil düzenleme</h3>
            <div class="menu-item">
                <a href="langs" style="margin-left: 10px;"><i class="fa-solid fa-globe"></i> Diller</a>
            </div>

            <div class="menu-item">
                <a href="keys" style="margin-left: 10px;"> <i class="fa-solid fa-key"></i> Anahtarlar</a>
            </div>

        </div>

        <div style="width: 100%;display: flex; flex-direction: column;">
            <div class="page-header">
                <h3><?= $pageTitle ?></h3>
            </div>