<footer id="footer" class="bg-primary border-0">
	<div class="container container-xl-custom pt-5 pb-3">
		<div class="row py-5 footer_div">
			<div class="col-md-4 col-lg-3 mb-4 mb-lg-0">
				<h4 class="font-weight-extra-bold text-5 ls-0"> <?=LH::t("address")?> </h4>
				<ul class="list list-unstyled">
				<li class="mb-1">
					<p class="mb-0">Yıldırım Beyazıt Mah.<br>Aşık Veysel Blv. Teknopoark 5.Bina No:67/4/24<br><br>Melikgazi/Kayseri</p>
</li>	
				</ul>
			</div>
			<div class="col-md-4 col-lg-2 mb-4 mb-lg-0">
				<h4 class="font-weight-extra-bold text-5 ls-0"><?=LH::t("communication")?></h4>
				<ul class="list-unstyled">
					<li class="mb-1">
					<?=LH::t("merkez_kayseri")?>
					</li>
					<li class="mb-1">
						<a href="tel:444 12 05" class="d-block line-height-2 mb-1">Phone:444 12 05</a>
					</li>
					<li class="mb-1">
					<a href="mailto:info@solidelectron.com" >info@solidelectron.com</a>
					</li>


				</ul>
			</div>
			<div class="col-md-4 col-lg-3 mb-4 mb-md-0">
				<h4 class="font-weight-extra-bold text-5 ls-0"><?=LH::t("services")?></h4>
				<ul class="list-unstyled">
					<li class="mb-1">
						<a href="/<?= $lang ?>/water-management"><?=LH::t("water_management")?></a>
					</li>
					<li class="mb-1">
						<a href="/<?= $lang ?>/energy-efficiency"><?=LH::t("energy_efficiency")?></a>
					</li>
					<li class="mb-1">
						<a href="/<?= $lang ?>/predixi-cloud-water-control-software"><?=LH::t("predixi_cloud_water_c_s")?></a>
					</li>

				</ul>
			</div>
			<div class="col-md-4 col-lg-2 mb-4 mb-md-0">
				<h4 class="font-weight-extra-bold text-5 ls-0">About</h4>
				<ul class="list-unstyled">
					<li class="mb-1">
						<a href="/<?= $lang ?>/about"><?=LH::t("about_us")?></a>
					</li>
					<li>
						<a href="/<?= $lang ?>/contact"><?=LH::t("send_message")?></a>
					</li>
					<li>
						<a href="/<?= $lang ?>/privacy-policy" >
						<?=LH::t("privacy_policy")?>
						</a>
					</li>
				</ul>
			</div>
			<div class="col-md-4 col-lg-2">
				<h4 class="font-weight-extra-bold text-5 ls-0"><?=LH::t("follow_us")?></h4>
				<ul class="social-icons social-icons-clean social-icons-icon-light">
					<li>
						<a href="https://www.linkedin.com/company/solid-electron/"><i class="fab fa-linkedin-in"></i></a>
					</li>
					<li>
						<a href="https://www.instagram.com/solidect/"><i class="fab fa-instagram"></i></a>
					</li>

				</ul>
			</div>
		</div>
	</div>
	<div class=" bg-primary">
		<div class="container container-xl-custom pb-4">

			<div class="row py-5 my-3">
				<div class="col text-center">
					


					<p class="text-3 mb-0">Solid Electron © <?= date("Y") ?>.</p>
				</div>
			</div>
		</div>
	</div>
</footer>

</div>

<!-- Vendor -->
<script src="/vendor/plugins/js/plugins.min.js"></script>


<!-- Theme Base, Components and Settings -->
<script src="/js/theme.js"></script>

<!-- Demo -->
<script src="/js/demos/demo-architecture-2.js"></script>

<!-- Theme Custom -->
<script src="/js/custom.js"></script>

<!-- Theme Initialization Files -->
<script src="/js/theme.init.js"></script>

<script async src="https://www.googletagmanager.com/gtag/js?id=G-7VMY1DJ9JN"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-7VMY1DJ9JN');
</script>

</body>

</html>