<section class="custom-page-header-1 page-header bg-primary border-0 z-index-1">
    <div class="custom-page-header-1-wrapper overflow-hidden">
        <div class="custom-bg-grey-1 py-3 appear-animation" data-appear-animation="maskUp" >
            <div class="container py-2 my-3">
                <div class="row">
                    <div class="col-md-12 align-self-center p-static text-center">
                        <div class="overflow-hidden mb-2">
                            <h1 class="font-weight-black text-9 mb-0 appear-animation" data-appear-animation="maskUp" ><?= $pageTitle ?></h1>
                        </div>
                        <div class="overflow-hidden mb-2">
                            <a href=""><h1  id="page_1" class="font-weight-black text-4 mb-0 appear-animation" data-appear-animation="maskUp" ></h1></a>
                            <h1 id="page_2" class="font-weight-black text-4 mb-0 appear-animation" data-appear-animation="maskUp" ><?= $pageTitle ?></h1>
                        </div>
                    </div>
                 
                </div>
            </div>
        </div>
    </div>
</section>