
<?php
include V_PATH . '/_parts/_head.phtml';
?>
<div role="main" class="main">
    <section class="custom-page-header-1 page-header page-header-modern page-header-lg bg-primary border-0 z-index-1 my-0">
        <div class="custom-page-header-1-wrapper overflow-hidden">
            <div class="custom-bg-grey-1 py-3 appear-animation" data-appear-animation="maskUp" data-appear-animation-delay="200">
                <div class="container py-2 my-2">
                    <div class="row">
                        <div class="col-md-12 align-self-center p-static text-center">
                            <div class="overflow-hidden mb-2">
                                <h1 class="font-weight-black text-12 mb-0 appear-animation" data-appear-animation="maskUp" data-appear-animation-delay="200">Error</h1>
                            </div>
                        </div>
                        <div class="col-md-12 align-self-center">
                            <div class="overflow-hidden">
                                <ul class="custom-breadcrumb-style-1 breadcrumb breadcrumb-light custom-font-secondary d-block text-center custom-ls-1 text-5 appear-animation" data-appear-animation="maskUp" data-appear-animation-delay="250">
                    
                                    <li class="text-transform-none active" style="color:#000">
                                          <?= $errCode ?>
                                       Error CODE <?= $errCode ?>
                                       Error MSG <?= $errMsg ?>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
</div>
<?php
include V_PATH . '/_parts/_footer.phtml';
?>